image: python:3.6

before_script:
  - python --version
  - pip install .[dev]

stages:
  - lint
  - test

lint:flake8:
  stage: lint
  script: flake8 apub tests examples setup.py

lint:pylint:
  stage: lint
  script: pylint apub tests examples setup.py

test:py36:
  image: python:3.6
  stage: test
  script: python setup.py test

test:py37:
  image: python:3.7
  stage: test
  script: python setup.py test

cover:
  stage: test
  script: pytest --cov-report term-missing --cov=apub tests/
