# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.6"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r requirements.txt
  - pip install coveralls

# command to run tests, e.g. python setup.py test
script: pytest --cov-report term-missing --cov=apub tests/

# command to run code quality tool
after_script: pylint apub tests examples setup.py

after_success: coveralls

sudo: false
