title: My book
author: Max Mustermann
language: en

chapters:
  - src: first_chapter.md
  - src: second_chapter.md
  - src: unfinished_chapter.md
    publish: False

substitutions:
  - old: Some
    new: Thing
  - pattern: \+\+(?P<text>.*?)\+\+
    replace_with: <span class="small-caps">\g<text></span>

ebookconvert_params:
  default:
    - --level1-toc=//h:h1
    - --level2-toc=//h:h2
    - --change-justification=left
  mobi:
    - --mobi-file-type=both

stylesheet: style.css

outputs:
  - type: html
    output: example.html
  - type: ebook
    output: example.epub
  - type: ebook
    output: example.mobi
    ebookconvert_params:
      - default
      - mobi
  - type: ebook
    output: overridden_stylesheet.epub
    stylesheet: overridden.css
