title: My book
author: Max Mustermann
language: en

chapters:
  - src: first_chapter.md
  - src: second_chapter.md
  - src: unfinished_chapter.md
    publish: False

substitutions:
  - old: Some
    new: Thing
  - pattern: \+\+(?P<text>.*?)\+\+
    replace_with: <span class="small-caps">\g<text></span>

ebookconvert_params:
  - level1-toc=//h:h1
  - level2-toc=//h:h2
  - change-justification=left

stylesheet: style.css

outputs:
  - type: html
    output: example.html
  - type: ebookconvert
    output: example.epub
  - type: ebookconvert
    output: example.mobi
    ebookconvert_params:
      - mobi-file-type=both
  - type: ebookconvert
    output: additional_stylesheet.epub
    stylesheet: additional.css
